### ISSUE TITLE
nopCommerce 4.40.4 change on html not working anymore

### ISSUE THREAD

**Issue by jimonreal** [nopSolutions/PayPal-SmartButtons-plugin-for-nopcommerce#17]
In the PaymentInfo view

input.payment-info-next-step-button changed to button.payment-info-next-step-button

The plugin does not work on nopCommerce 4.40.4

**Comment by RomanovM** [comment]
Starting from 4.40.4 _PayPal Commerce_ plugin is used instead of _PayPal SmartButtons_ plugin (download it [here](https://www.nopcommerce.com/paypal-commerce-the-official-integration)). 
_PayPal SmartButtons_ support and development have been discontinued, but anyway you can customize it and add any changes.
